### ISSUE TITLE
desplegar divs por clase jQuery

### ISSUE THREAD

**Issue by oscardorrego** [estenoesmiputonombre/valuebetsmining#1]
tengo varios h1 cada uno con una clase distinta ,y con cada clase un div que quiero que se muestre u oculte al pulsar el h1

**Comment by estenoesmiputonombre** [comment]
Saludos,
Esta sería una posibilidad usando el método index y selector eq. Obvia el estilo y modifícalo a tu gusto:

`<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script>
        $(() => {
            $("h1.open").click(function() {
                $(`div.open:eq(${$("h1.open").index(this)})`).toggle();
            });
        })
    </script>
    <style>
        div.up {
            width: 50%;
            background-color: gray;
        }
        div.open {
            display: none;
            background-color: greenyellow;
        }
        h1.open {
            background-color: gray;
        }
    </style>
</head>
<body>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
</body>
</html>`

**Comment by MrTimeout** [comment]
Saludos,
Esta sería una posibilidad usando el método index y selector eq. Obvia el estilo y modifícalo a tu gusto:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script>
        $(() => {
            $("h1.open").click(function() {
                $(`div.open:eq(${$("h1.open").index(this)})`).toggle();
            });
        })
    </script>
    <style>
        div.up {
            width: 50%;
            background-color: gray;
        }
        div.open {
            display: none;
            background-color: greenyellow;
        }
        h1.open {
            background-color: gray;
        }
    </style>
</head>
<body>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
    <div class="up">
        <h1 class="open">Ábreme</h1>
        <div class="open">
            Aquí mostramos información
        </div>
    </div>
</body>
</html>```

**Comment by oscardorrego** [comment]
perfecto muchas garcias
